version: "3.3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github-user-details
    ports:
    - "0.0.0.0:5432:5432"