openapi: 3.0.1
info:
  title: Github user details
  version: 0.0.1
  description: |
    Github user details API

servers:
  - url: http://localhost:8080

security:
  - UserSecurity: [ ]

tags:
  - name: Github user details
    description: Github user details API.

paths:
  /github-user-details/api/v1/users/{login}:
    get:
      summary: Retrieve Github user details
      description: |
        Retrieves Github uses details for given login.
      tags:
        - users
      operationId: getGithubUserDetails
      parameters:
        - $ref: '#/components/parameters/login'
      responses:
        200:
          $ref: '#/components/responses/GithubUserDetailsResponse'
        404:
          description: NotFound
        500:
          description: Internal Server Error
components:
  parameters:
    login:
      name: login
      in: path
      description: 'Github login'
      required: true
      example: "bartekqx"
      schema:
        type: string

  responses:
    GithubUserDetailsResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GithubUserDetails'
  schemas:
    GithubUserDetails:
      type: object
      properties:
        id:
          description: User id
          example: 518723
          type: integer
          format: int64
        login:
          description: User's login at github.com
          example: bartekqx
          type: string
        name:
          description: User name
          example: Bartek
          type: string
        type:
          description: User account type
          example: User
          type: string
        avatarUrl:
          description: Avatar url
          example: https://avatars.githubusercontent.com/u/73738415?v=4
          type: string
        createdAt:
          description: Account creation timestamp
          example: 2020-10-31T09:05:27Z
          type: string
        updatedAt:
          description: Last account update timestamp
          example: 2021-10-31T09:05:27Z
          type: string
        calculations:
          description: Custom calculations
          example: 6.75
          type: number
          format: double
  securitySchemes:
    UserSecurity:
      type: http
      scheme: basic